package org.highschool.forms;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.GroupLayout;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

import org.highschool.jdbc.ConnectionSQLite;

/**
 * Cette Classe permet avec le Framework d'affichage swing
 * de Java disponible dans le JRE de cree differents UI
 * pour interagir avec un utilisateur
 * 
 * C'est la fenetre principale de l'application notre application
 * HighSchoolManager. Elle nous permettra d'aller dans les differents menus
 *
 */
public class HighSchoolManager extends JFrame{

	private static final long serialVersionUID = -1693776512518498816L;
	
	private static Logger LOG = Logger.getLogger(HighSchoolManager.class.getName());
	
	private JDesktopPane desktopPane;
    private JMenuItem exitMenuItem;
    private JMenu fileMenu;
    private JMenuBar menuBar;
    private JMenuItem openMenuItem1;
    private JMenuItem openMenuItem2;
	
    public HighSchoolManager() throws SQLException{
        initComponents();
        this.setTitle("Gestion Collège");
        this.setLocationRelativeTo(null);//Afficher au centre de l'écran
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws SQLException 
     */
    private void initComponents() throws SQLException {
    	
    	//Initialisation de la connexion a la base de données
    	if(!ConnectionSQLite.connect()) {
    		throw new SQLException("erreur de connexion a la base de donnees");
    	}
    	
        desktopPane = new JDesktopPane();
        menuBar = new JMenuBar();
        fileMenu = new JMenu();
        openMenuItem1 = new JMenuItem();
        openMenuItem2 = new JMenuItem();
        exitMenuItem = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        openMenuItem1.setMnemonic('o');
        openMenuItem1.setText("Etudiant");
        openMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem1);
        
        openMenuItem2.setMnemonic('p');
        openMenuItem2.setText("Professeur");
        openMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItem2ActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem2);
        
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt){
            	try {
            		exitMenuItemActionPerformed(evt);
            	}catch(SQLException e) {
            		LOG.severe("erreur avec la connexion: " + e.getMessage());
            		System.exit(0);
            	}
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
    	//Initialisation de la connexion a la base de données
    	if(!ConnectionSQLite.disconnect()) {
    		throw new SQLException("erreur de deconnexion a la base de donnees");
    	}
        System.exit(0);
    }

    private void openMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
        StudentForm ef = new StudentForm();
        desktopPane.add(ef);
        ef.setVisible(true);
    }
    
    private void openMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
        TeacherForm ef = new TeacherForm();
        desktopPane.add(ef);
        ef.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            LOG.log(Level.SEVERE, "Class not found:", ex);
        } catch (InstantiationException ex) {
        	LOG.log(Level.SEVERE, "not able to instatiate class: ", ex);
        } catch (IllegalAccessException ex) {
        	LOG.log(Level.SEVERE, "Illegal access: ", ex);
        } catch (UnsupportedLookAndFeelException ex) {
        	LOG.log(Level.SEVERE, "Unsupported look: ", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	try {
            		new HighSchoolManager().setVisible(true);
            	}catch(SQLException ex) {
            		LOG.log(Level.SEVERE, "erreur avec la connexion: " , ex);
            		System.exit(0);
            	}
            }
        });
    }

}
